# Generated by Django 4.1.7 on 2023-02-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.CharField(max_length=64)),
                ('longitude', models.CharField(max_length=64)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('price_level', models.CharField(max_length=12)),
            ],
        ),
    ]
